Description: Config for Configurator App
Type: Configurator

#InstallDirectory: ..\..\install\
#InjectorDirectory: ..\..\apps\injector\
#TestRunnerDirectory: ..\..\apps\test_runner\
#CiDirectory: ..\..\ci\
#TransmitterDirectory: ..\..\components\transmitter\ # located somewhere in the distribution of Drill4Net
#PluginDirectory: ..\..\components\transmitter_plugins\  # Agent's plugins (IEngineContexters) - located somewhere in the distribution of Drill4Net

InstallDirectory: d:\Projects\EPM-D4J\Distributions\debug\Drill4Net_dis\install\
InjectorDirectory: ..\..\Drill4Net.Injector.App\net6.0\
TestRunnerDirectory: ..\..\Drill4Net.Agent.TestRunner\net6.0\
CiDirectory: d:\Projects\EPM-D4J\Distributions\debug\Drill4Net_dis\ci\
TransmitterDirectory: ..\..\Drill4Net.Agent.Transmitter\netstandard2.0\ # located somewhere in the distribution of Drill4Net
PluginDirectory: ..\..\  # plugins - located somewhere in the distribution of Drill4Net

ExternalEditor: # external editor to edit the configs
ProjectsDirectory: d:\Projects\EPM-D4J\Distributions\debug\projects\ # default project sources' directory for CI integrations