using System;

namespace Drill4Net.Profiling.Tree
{
    /// <summary>
    /// Cross-cutting point for injection code located in <see cref="InjectedMethod"/>
    /// </summary>
    [Serializable]
    public class CrossPoint : InjectedSimpleEntity
    {
        /// <summary>
        /// Uid of <see cref="CrossPoint"/>
        /// </summary>
        public string PointUid { get; set; }

        /// <summary>
        /// Some local Id of <see cref="CrossPoint"/> (may be a position of the instruction in IL code)
        /// </summary>
        public string PointId { get; set; }

        /// <summary>
        /// End-to-end index of the method instruction, taking into account
        /// only the business parts of the source code moved by the compiler
        /// to the classes generated by it
        /// </summary>
        public int BusinessIndex { get; set; }

        /// <summary>
        /// Semantic type of <see cref="CrossPoint"/> 
        /// </summary>
        public CrossPointType PointType { get; set; }

        #region PDB
        public int? RowStart { get; set; }
        public int? RowEnd { get; set; }
        public int? ColStart { get; set; }
        public int? ColEnd { get; set; }
        #endregion

        /************************************************************************/

        /// <summary>
        /// Create the cross-cutting point for the injection code located in <see cref="InjectedMethod"/>
        /// </summary>
        /// <param name="pointUid"></param>
        /// <param name="pointId"></param>
        /// <param name="businessIndex"></param>
        /// <param name="pointType"></param>
        public CrossPoint(string pointUid, string pointId, int businessIndex, CrossPointType pointType):
            base(null)
        {
            PointUid = pointUid;
            PointId = pointId;
            BusinessIndex = businessIndex;
            PointType = pointType;
        }

        /************************************************************************/

        public override string ToString()
        {
            return $"P: {PointUid}: {PointType}_{PointId}";
        }
    }
}
